# Generated by Django 3.1.4 on 2021-06-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0003_auto_20210601_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
